=== juancarlosdcbenitez/LLMM/Tema5/DTD/Ejercicios_adicionales/Ejercicio2/alumnos.dtd
<!ELEMENT alumnos (alumno+)>

<!ELEMENT alumno (nombre, apellidos, domicilio, telefono+, equipo?, aficion*, origen, comentarios?, notas)>
<!ATTLIST alumno num_alumno ID #REQUIRED>
<!ATTLIST alumno altura CDATA #IMPLIED>
<!ATTLIST alumno sexo (H|M) #IMPLIED>
<!ATTLIST alumno ayuda IDREF #IMPLIED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT domicilio (#PCDATA)>

<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono tipo (propio|padre|madre|tutor) #REQUIRED>

<!ELEMENT equipo (#PCDATA)>
<!ELEMENT aficion (#PCDATA)>

<!ELEMENT origen (provincia | pais)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT pais (#PCDATA)>

<!ELEMENT comentarios ANY>

<!ELEMENT notas (evaluacion, calificacion)+>
<!ELEMENT evaluacion (#PCDATA)>
<!ELEMENT calificacion (#PCDATA)>

=== juancarlosdcbenitez/LLMM/Tema5/DTD/Ejercicios adicionales/Ejercicio 2/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos SYSTEM "alumnos.dtd">
<alumnos>

    <alumno num_alumno="a1" altura="178" sexo="H">
        <nombre>Juan Carlos</nombre>
        <apellidos>Del Carmen Benítez</apellidos>
        <domicilio>Calle Marismas Puntal de la Marina 27, Huelva</domicilio>
        <telefono tipo="propio">617012651</telefono>
        <telefono tipo="madre">600333444</telefono>
        <equipo>Baloncesto</equipo>
        <aficion>Videojuegos</aficion>
        <aficion>Programación</aficion>
        <origen>
            <provincia>Huelva</provincia>
        </origen>
        <comentarios>
            Alumno muy participativo.
        </comentarios>
        <notas>
            <evaluacion>1ª evaluación</evaluacion>
            <calificacion>8.5</calificacion>
            <evaluacion>2ª evaluación</evaluacion>
            <calificacion>9.0</calificacion>
        </notas>
    </alumno>

    <alumno num_alumno="a2" sexo="M" ayuda="a1">
        <nombre>Jacobo</nombre>
        <apellidos>Martín Salamanca</apellidos>
        <domicilio>Avenida Andalucía 25, Huelva</domicilio>
        <telefono tipo="padre">600555666</telefono>
        <aficion>Lectura</aficion>
        <aficion>Natación</aficion>
        <origen>
            <pais>España</pais>
        </origen>
        <notas>
            <evaluacion>1ª evaluación</evaluacion>
            <calificacion>7.0</calificacion>
        </notas>
    </alumno>

</alumnos>
