=== juancarlosdcbenitez/LLMM/Tema 5/XSD/Ejercicio 2/alumnos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="alumnos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumno" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="apellidos" type="xs:string"/>
                            <xs:element name="domicilio" type="xs:string"/>
                            <xs:element name="telefono" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="tipo" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="propio"/>
                                                        <xs:enumeration value="padre"/>
                                                        <xs:enumeration value="madre"/>
                                                        <xs:enumeration value="tutor"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="equipo" type="xs:string" minOccurs="0"/>
                            <xs:element name="aficion" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>

                            <xs:element name="origen">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element name="provincia" type="xs:string"/>
                                        <xs:element name="pais" type="xs:string"/>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="comentarios" minOccurs="0">
                                <xs:complexType mixed="true">
                                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                        <xs:any processContents="lax"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="notas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="evaluacion" type="xs:string" maxOccurs="unbounded"/>
                                        <xs:element name="calificacion" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>

                        <xs:attribute name="num_alumno" type="xs:ID" use="required"/>
                        <xs:attribute name="altura" type="xs:positiveInteger" use="optional"/>
                        <xs:attribute name="sexo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="H"/>
                                    <xs:enumeration value="M"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="ayuda" type="xs:IDREF" use="optional"/>

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== juancarlosdcbenitez/LLMM/Tema5/XSD/Ejercicio 2/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="alumnos.xsd">

    <alumno num_alumno="a1" altura="178" sexo="H">
        <nombre>Juan Carlos</nombre>
        <apellidos>Del Carmen Benítez</apellidos>
        <domicilio>Calle Marismas Puntal de la Marina 27, Huelva</domicilio>
        <telefono tipo="propio">617012651</telefono>
        <telefono tipo="madre">600333444</telefono>
        <equipo>Baloncesto</equipo>
        <aficion>Videojuegos</aficion>
        <aficion>Programación</aficion>
        <origen>
            <provincia>Huelva</provincia>
        </origen>
        <comentarios>
            Alumno muy participativo.
        </comentarios>
        <notas>
            <evaluacion>1ª evaluación</evaluacion>
            <calificacion>8.5</calificacion>
            <evaluacion>2ª evaluación</evaluacion>
            <calificacion>9.0</calificacion>
        </notas>
    </alumno>

    <alumno num_alumno="a2" sexo="M" ayuda="a1">
        <nombre>Jacobo</nombre>
        <apellidos>Martín Salamanca</apellidos>
        <domicilio>Avenida Andalucía 25, Huelva</domicilio>
        <telefono tipo="padre">600555666</telefono>
        <aficion>Lectura</aficion>
        <aficion>Natación</aficion>
        <origen>
            <pais>España</pais>
        </origen>
        <comentarios/>
        <notas>
            <evaluacion>1ª evaluación</evaluacion>
            <calificacion>7.0</calificacion>
        </notas>
    </alumno>

</alumnos>
