=== juancarlosdcbenitez/LLMM/Tema 5/DTD/Ejercicio de Structuredauthoring/resume.dtd
<!ELEMENT resume (personal-info, education*, history*, skills)>

<!ELEMENT personal-info (name, email, phone, location)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT location (city, state)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>

<!ELEMENT education (school+)>
<!ELEMENT school (name, degree, year, location)>
<!ATTLIST school type (university | college | vocational | other) #REQUIRED>
<!ELEMENT degree (#PCDATA)>
<!ELEMENT year (#PCDATA)>

<!ELEMENT history (job+)>
<!ELEMENT job (title, company, start, end?, description)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT company (#PCDATA)>
<!ELEMENT start (#PCDATA)>
<!ELEMENT end (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT skills (skill+)>
<!ELEMENT skill (#PCDATA)>

=== juancarlosdcbenitez/LLMM/Tema5/DTD/Structuredauthoring/resume.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resume SYSTEM "resume.dtd">
<resume>

  <personal-info>
    <name>Juan Pérez</name>
    <email>juan@example.com</email>
    <phone>600123456</phone>
    <location>
      <city>Huelva</city>
      <state>Andalucía</state>
    </location>
  </personal-info>

  <education>
    <school type="college">
      <name>Austin Community College</name>
      <degree>Associates of Applied Science</degree>
      <year>1988</year>
      <location>
        <city>Austin</city>
        <state>Texas</state>
      </location>
    </school>
  </education>

  <history>
    <job>
      <title>Web Developer</title>
      <company>TechCorp</company>
      <start>2019</start>
      <end>2023</end>
      <description>Frontend development and UI optimization.</description>
    </job>
  </history>

  <skills>
    <skill>HTML</skill>
    <skill>CSS</skill>
    <skill>JavaScript</skill>
  </skills>

</resume>
